name: weighing_mobile
description: "Busan Smart Weighing System Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  go_router: ^14.0.0
  provider: ^6.1.0
  intl: ^0.19.0
  share_plus: ^7.0.0
  url_launcher: ^6.2.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
